name: Analyse du code avec SonarCloud
uses: SonarSource/sonarcloud-github-action@v2
env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
with:
      args: >
       -Dsonar.organization=elmazoughi
       -Dsonar.projectKey=elmazoughi_tp-ci-cd
       -Dsonar.sources=.